-- Basic configuration
require('core.plugins')
require('core.configs')

-- Plugins
require('plugins.autopairs')
require('plugins.neotree')
require('plugins.tt')
require('plugins.treesitter')
require('plugins.telescope')
require('plugins.autotag')
require('plugins.bufferlines')
require('plugins.comments')
require('plugins.dashboard')
require('plugins.gitsigns')
require('plugins.lualine')
require('plugins.outline')
require('plugins.whichkey')
require('plugins.cmp')
require('plugins.lsp')
require('plugins.mason')
require('plugins.conform')
require('plugins.ufo')
